version: "3.8"
services:
  notebook:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: jupyter:python-3.10.5
    container_name: template
    ports:
      - "8887:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - ./:/home/jovyan/notebook
      - ./.jupyter:/home/jovyan/.jupyter
    command: start-notebook.sh --NotebookApp.token=''
